


# 2023.11.22 morning
```
gpt-4p     =            gpt-4-1106-preview@openai  , context length: 128000, prompt: $ 10.00/Mt, completion: $ 30.00/Mt 14.6 tk/s
gpt-4v     =        gpt-4-1106-vision-preview@openai  , context length: 128000, prompt: $ 10.00/Mt, completion: $ 30.00/Mt ERROR: the server responded with status 404
gpt-4     =                gpt-4-32k@openai  , context length: 16384, prompt: $ 60.00/Mt, completion: $120.00/Mt ERROR: {
 "message": "The model `gpt-4-32k` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.",
 "type": "invalid_request_error",
 "param": null,
 "code": "model_not_found"
}
gpt-3.5    =              gpt-3.5-turbo@openai  , context length: 16384, prompt: $ 1.00/Mt, completion: $ 2.00/Mt 33.3 tk/s -> gpt-3.5-turbo-0613
```

# 2023.11.22 evening
```
gpt-4p         =                       gpt-4-1106-preview@openai    , context length: 128000, prompt: $ 10.00/Mt, completion: $ 30.00/Mt  13.7 tk/s
gpt-4v         =                gpt-4-1106-vision-preview@openai    , context length: 128000, prompt: $ 10.00/Mt, completion: $ 30.00/Mt ERROR: the server responded with status 404
gpt-4          =                                gpt-4-32k@openai    , context length:  16384, prompt: $ 60.00/Mt, completion: $120.00/Mt ERROR: the server responded with status 404
gpt-3.5        =                            gpt-3.5-turbo@openai    , context length:  16384, prompt: $  1.00/Mt, completion: $  2.00/Mt  40.4 tk/s -> gpt-3.5-turbo-0613
```
